(function(){var virb={};virb.site={scriptLoads:[],config:{},objs:{},init:function(args){var self=this;$.each(args,function(key){self.config[key]=args[key];});var $html=$('html');this.config.isTouch=$html.hasClass('touch')||navigator.msMaxTouchPoints?true:false;this.config.msTouch=window.navigator.msPointerEnabled&&navigator.msMaxTouchPoints?true:false,this.config.isIE7=$html.hasClass('ie7')||$html.hasClass('lt-ie8')?true:false;this.config.isIE=$html.hasClass('ie')?true:false;this.config.isRetina=window.devicePixelRatio>1?true:false;if(this.config.isMobile){$html.addClass('is-mobile');}
virb.log(window.devicePixelRatio);this.cart=CartDataManager;this.initObjs();this.attachEvents();},initObjs:function(){this.objs.cartLink=$('.cart-link');this.objs.cartLinkLabel=this.objs.cartLink.find('.label');this.objs.navToggle=$('.toggle a');this.objs.nav=this.objs.navToggle.closest('nav');if(this.cart.getProductCount()>0){this.objs.cartLink.addClass('show-cart');$('.has-store').addClass('show-cart');}
this.objs.cartLinkTotal=$('<span>');this.objs.cartLinkTotalCount=$('<span>',{'class':'total'}).append(this.cart.getProductCount());var paren=$('<span>',{'class':'paren'});this.objs.cartLinkTotal.append(' ').append(paren.clone().append('(')).append(this.objs.cartLinkTotalCount).append(paren.clone().append(')'));this.objs.cartLinkLabel.append(this.objs.cartLinkTotal);},attachEvents:function(){virb.log('site: attach events');var self=this;this.objs.cartLink.bind('update.cart.virb',function(){var count=self.cart.getProductCount();self.objs.cartLinkTotalCount.text(count);});this.objs.navToggle.bind('click',function(e){e.preventDefault();var $this=$(this);var $menu=$('#menu');$menu.css({opacity:0,display:'block',height:'auto'});var listHeight=$menu.outerHeight();if(self.objs.nav.hasClass('open')){$menu.css({opacity:1}).animate({height:0,opacity:0,marginBottom:0},function(){$(this).css({height:0,display:'none'});self.objs.nav.toggleClass('open');});}else{$menu.css({height:0}).animate({opacity:1,height:listHeight},function(){$(this).css({height:'auto'});});self.objs.nav.toggleClass('open');}});$("#menu li.section span").bind('click',function(){var $this=$(this).closest('li');$sectionUl=$this.find('ul:first');$this.toggleClass('open');});},virbUrl:function(path){return'http://'+[this.config.virbDomain,path].join('/');},url:function(path){return'http://'+[this.config.requestDomain,path].join('/');},currentPageUrl:function(){return this.url(this.config.pageUrl);},addScript:function(url){if(!this.scriptLoads[url]){this.scriptLoads[url]=1;}
else
{this.scriptLoads[url]++;}
if(this.scriptLoads[url]<=10){setTimeout(function(){$('script[href^="'+url+'"]').remove();$.getScript(url+'&cacheb='+Math.random());},500);}},trackEvent:function(category,action,label){if(window._gaq){_gaq.push(['_trackEvent',category,action,label]);}}};virb.log=function(){if(virb.site.config.debug){try{var args=Array.prototype.slice.call(arguments),log=Function.prototype.bind.call(console.log,console);log.apply(this,args);}catch(e){}}};virb.cookie=function(key,value,options){if(arguments.length>1&&(!/Object/.test(Object.prototype.toString.call(value))||value===null||value===undefined)){options=$.extend({},options);if(value===null||value===undefined){options.expires=-1;}
if(typeof options.expires==='number'){var days=options.expires,t=options.expires=new Date();t.setDate(t.getDate()+days);}
value=String(value);return(document.cookie=[encodeURIComponent(key),'=',options.raw?value:encodeURIComponent(value),options.expires?'; expires='+options.expires.toUTCString():'',options.path?'; path='+options.path:'',options.domain?'; domain='+options.domain:'',options.secure?'; secure':''].join(''));}
options=value||{};var decode=options.raw?function(s){return s;}:decodeURIComponent;var pairs=document.cookie.split('; ');for(var i=0,pair;pair=pairs[i]&&pairs[i].split('=');i++){if(decode(pair[0])===key){return decode(pair[1]||'');}}
return null;};var CartDataManager={add:function(product){var products=this.getProducts();if(!products[virb.store.getType()]){products[virb.store.getType()]=[];}
products[virb.store.getType()].push(product);this.saveState(JSON.stringify(products));$.event.trigger('update.cart.virb');},remove:function(type,uid){var products=this.getProducts();for(var i=0;i<products[type].length;i++){if(products[type][i].u===uid){products[type].splice(i,1);}}
this.saveState(JSON.stringify(products));$.event.trigger('update.cart.virb');$.event.trigger('itemRemoved.cart.virb',[uid]);},empty:function(type){var products=this.getProducts();delete products[type];this.saveState(JSON.stringify(products));$.event.trigger('update.cart.virb');},saveState:function(data){virb.log(data);virb.cookie('products',data,{expires:7,path:'/'});},getProducts:function(){var products=virb.cookie('products');if(products){products=$.parseJSON(products);if(products.etsy||products.bigcartel){return products;}}
return{};},getProductCount:function(){var products=this.getProducts(),total=0;$.each(products,function(key,value){total+=value.length;});return total;},getTotal:function(type){var products=this.getProducts(),total=0;if(products[type]){for(var i=0;i<products[type].length;i++){total+=products[type][i].p*1;}}
return total.toFixed(2);}};iconMap={'ie7':{"⏩":"›","⏪":"‹","ⅱ":"ll","▶":">","×":"x"},'winPhone7':{"⏩":"›","⏪":"‹","ⅱ":"ll"}}
$.fn.fixIcons=function(){return this.each(function(){var $this=$(this);if(false!==virb.site.config.isIE7){swapIcons($this,'ie7');$this.addClass('data-icon').prepend('<span>'+$this.data('icon')+'</span>');}else if(false!==virb.site.config.isWindowsPhone7){swapIcons($this,'winPhone7');}});};var swapIcons=function($element,mapKey){$.each(iconMap[mapKey],function(index,value){if(escape(index)==escape($element.data('icon'))){$element.attr({'data-icon':value});$element.data({'icon':value});}else if(escape(index)==escape($element.data('icon-pause'))){$element.attr({'data-icon-pause':value});$element.data({'icon-pause':value});}});};$.fn.disableSelection=function(){return this.attr('unselectable','on').css('user-select','none').on('selectstart',false);};String.prototype.truncate=function(length){var str=''+this;if(str.length>length){return str.substring(0,length)+'&hellip;';}
return str;};getFlashMovie=function(movieName){var isIE=navigator.appName.indexOf("Microsoft")!=-1;flashMovie=(isIE)?window[movieName]:document[movieName];return flashMovie;}
aspectRatio=function(originalWidth,originalHeight,args){if(0==originalHeight||0==originalWidth){virb.log('Aspect ratio, Width: '+originalWidth+' Height: '+originalHeight);return{'width':originalWidth,'height':originalHeight};}
var height=originalHeight;var width=originalWidth;if(args.targetHeight){ratio=args.targetHeight/originalHeight;}else{ratio=args.targetWidth/originalWidth;}
if(args.targetHeight){height=args.targetHeight;width=Math.floor(originalWidth*ratio);}else{width=args.targetWidth;height=Math.floor(originalHeight*ratio);}
return{'width':width,'height':height};}
$(".share-label").click(function(){$(this).parent().parent().toggleClass("open");});window.virb=virb;$(function(){var getShareCount=function($share){var fullUrl;var shareUrl=$share.closest('.share-buttons').data('share-url');var type=$share.attr('class');switch(type){case'facebook':fullUrl='http://graph.facebook.com/?id='+shareUrl+'&callback=';break;case'twitter':fullUrl='http://cdn.api.twitter.com/1/urls/count.json?url='+shareUrl+'&jsonp=';break;case'linkedin':fullUrl='http://www.linkedin.com/countserv/count/share?format=jsonp&url='+shareUrl+'&jsonp=';break;case'pinterest':fullUrl='http://widgets.pinterest.com/v1/urls/count.json?url='+shareUrl+'&jsonp=';break;default:return;break;}
$.ajax({url:fullUrl,type:'GET',dataType:"jsonP",success:function(result){handleShareCount($share,result);}});};var handleShareCount=function($share,result){var count=0;var type=$share.attr('class');var $count=$share.find('.count');switch(type){case'facebook':if(result.shares){count=result.shares;}
break;case'twitter':case'linkedin':case'pinterest':if(result.count){count=result.count;}
break;default:return;break;}
$count.html(count);if(count>0){$count.show();}};$('.share-buttons').each(function(){$this=$(this);var shareUrl=$this.data('share-url');$this.find('li').each(function(){getShareCount($(this));});});virb.site.init(siteSettings);if(parent!==window){try{parent.virb.$.customize.pageReady(virb.site.config.pageUrlId);}catch(e){}}
$('[data-icon]').fixIcons();});})();;(function(){var useFlash=(false===(Modernizr.audio&&Modernizr.audio.mp3!==''));var Player=function(element){this.objs={};var self=this;if(useFlash){if($('#virbMedia').length===0){this.addFlashPlayer(function(){self.objs.flashMovie=$('#virbAudioPlayer')[0];});}else{self.objs.flashMovie=$('#virbAudioPlayer')[0];}}
this.objs.element=$(element);this.objs.tracks=[];this.objs.element.data('audio-player',this);this.objs.element.data('singular',(this.objs.element.attr('data-behavior')==='singular-control'));this.objs.element.find('ol li').each(function(i){self.objs.tracks.push(new Track(self,this));});};Player.prototype={singularControl:false,constructor:Player,addFlashPlayer:function(callback)
{$('body').prepend('<div class="media virbMedia" style="position:absolute;"><span id="replace_mediaAudioPlayer"></span></div>');var flashvars={virb_domain_secure:'http://'+virb.site.config.virbDomain};var params={name:'virbAudioPlayer',allowScriptAccess:'always',wmode:'transparent'};var attributes={wmode:'transparent',bgcolor:'',name:'virbAudioPlayer',id:'virbAudioPlayer'};swfobject.embedSWF('http://'+virb.site.config.virbCDNDomain+'/_assets/_swf/virb_audio_js.swf','replace_mediaAudioPlayer',"1","1","9.0.0",false,flashvars,params,attributes,callback);}};var Track=function(player,track){this.objs={};this.objs.player=player;this.objs.element=$(track);this.objs.audio=this.objs.element.find('audio');this.objs.time=this.objs.element.find('.time');this.objs.barContainer=this.objs.element.find('.length');this.objs.amountPlayed=this.objs.element.find('.length .progress');this.objs.amountLoaded=this.objs.element.find('.length .load');this.objs.playButton=this.objs.element.find('.controls .play-pause');this.objs.nextButton=this.objs.element.find('.controls .next');this.objs.prevButton=this.objs.element.find('.controls .previous');this.objs.element.data('audio-player-track',this);this.objs.playButton.bind('click',$.proxy(this.select,this));this.objs.element.bind('play.audio.virb',$.proxy(this.pauseSelf,this));if(this.objs.player.objs.element.data('singular')){this.objs.nextButton.bind('click',$.proxy(this.next,this));this.objs.prevButton.bind('click',$.proxy(this.previous,this));}
this.objs.audio.bind('timeupdate',$.proxy(this.updatePlayhead,this));this.objs.audio.bind('progress',$.proxy(this.updateBufferProgress,this));this.objs.audio.bind('ended',$.proxy(this.ended,this));};Track.prototype={constructor:Track,updatePlayhead:function(){var audio=this.objs.audio.get(0),duration=audio.duration,current=audio.currentTime,progress=(current/duration)*100,mins=parseInt(current/60,10),secs=parseInt(current-(mins*60),10);if(secs<10){secs='0'+secs;}
if(progress>=0){this.objs.amountPlayed.css({width:progress+'%'});}
this.objs.time.html(mins+':'+secs);},updateBufferProgress:function(){try{var audio=this.objs.audio.get(0),loaded=parseInt(((audio.buffered.end(0)/audio.duration)*100),10);if(loaded>=0){this.objs.amountLoaded.css({width:loaded+'%'});}}catch(e){}},seek:function(e){var ratio=(e.pageX-this.objs.barContainer.offset().left)/this.objs.barContainer.width(),track=this.objs.element;if(useFlash){this.objs.player.objs.flashMovie.seekTo(track.attr('data-uid'),ratio*100);return;}
var audio=this.objs.audio.get(0),duration=audio.duration;audio.currentTime=duration*ratio;},ended:function(e){virb.log('track ended');this.objs.amountPlayed.css({width:'0%'});this.objs.time.html('0:00');this.objs.audio.get(0).pause();this.objs.playButton.removeClass('pause');this.objs.audio.get(0).currentTime=0;var next=this.objs.element.next();if(next.length>0){this.next(e);}
return;},select:function(e){virb.log('select track');if(e!==undefined){e.preventDefault();}
var track=this.objs.element,id=track.attr('data-id'),uid=track.attr('data-uid'),playButton=this.objs.playButton,audio=this.objs.audio.get(0);track.show();this.objs.barContainer.bind('click',$.proxy(this.seek,this));if(useFlash){var movie=this.objs.player.objs.flashMovie,service='song';if(track.attr('data-source')!==undefined&&track.attr('data-source')!='virb'){service=track.attr('data-source');}
movie.retrieveSong(track.attr('data-uid'),track.attr('data-id'),service);virb.$.audio.updateLoader=function(uid,loaded){track.find('.length .load').css({width:loaded+'%'});};virb.$.audio.updateTime=function(time,uid){track.find('.time').html(time);};virb.$.audio.updateProgress=function(progress,uid){track.find('.length .progress').css({width:progress+'%'});};}else{if(audio.paused){audio.play();$.event.trigger('play.audio.virb',[track]);playButton.addClass('pause');track.addClass('playing');track.removeClass('paused');if(track.attr('data-title')){virb.site.trackEvent('Audio','Play',track.attr('data-title'));}}else{audio.pause();$.event.trigger('pause.audio.virb',[track]);playButton.removeClass('pause');track.addClass('paused');track.removeClass('playing');}}
var self=this,playerElement=this.objs.player.objs.element;if(playerElement.data('singular')){var tracks=playerElement.data('audio-player').objs.tracks;$.each(tracks,function(i,value){if(value!==self){value.objs.element.hide();}});}},next:function(e){virb.log('next track');e.preventDefault();var next=this.objs.element.next();if(next.length===0){this.objs.nextButton.css('opacity',0.5);return;}
next.data('audio-player-track').select();},previous:function(e){e.preventDefault();var prev=this.objs.element.prev();if(prev.length===0){this.objs.prevButton.css('opacity',0.5);return;}
prev.data('audio-player-track').select();},pauseSelf:function(e,$track){if($track!==this.objs.element){this.objs.audio.get(0).pause();this.objs.playButton.removeClass('pause');}}};virb.$={audio:{}};$(function(){$('.audio-player').each(function(){new Player(this);});if(useFlash){$(document).bind('playing.track.event.audio.virb',function(e,uid){var element=$(this).find('.audio-player ol li[data-uid="'+uid+'"]');element.data('audio-player-track').objs.playButton.addClass('pause');});$(document).bind('pause.track.event.audio.virb',function(e,uid){var element=$(this).find('.audio-player ol li[data-uid="'+uid+'"]');element.data('audio-player-track').objs.playButton.removeClass('pause');});}});})();;(function(){$.fn.addTouch=function(callback){new TouchEvents(this);if(callback){this.bind('touch',callback);}
return this;};var TouchEvents=function($target){this.$target=$target;$target.css({'-ms-touch-action':'none'});var self=this;$target[0].addEventListener('click',function(event){if(self.moved){if(true===self.msTouch){event.preventDefault();}
event.stopPropagation();}},true);$target.on(this.eventMap[this.touchType].start,$.proxy(this.touchstart,this));$target.on(this.eventMap[this.touchType].move,$.proxy(this.touchmove,this));$target.on(this.eventMap[this.touchType].end,$.proxy(this.touchend,this));};TouchEvents.prototype={msTouch:window.navigator.msPointerEnabled&&navigator.msMaxTouchPoints?true:false,touchType:window.navigator.msPointerEnabled&&navigator.msMaxTouchPoints?'ms':'webkit',eventMap:{ms:{'start':'MSPointerDown','move':'MSPointerMove','end':'MSPointerUp'},webkit:{'start':'touchstart','move':'touchmove','end':'touchend'}},constructor:TouchEvents,setDefaults:function(e){this.latestTap=0;this.lastMoveTime=false;this.fingerCount=0;this.moved=false;this.direction=false;this.offset={x:0,y:0};this.startPosition=this.getPosition(e.originalEvent);this.lastPosition=this.currentPosition=this.startPosition;},getPosition:function(e){if(true===this.msTouch){return{x:e.clientX.toFixed(0),y:e.clientY.toFixed(0)};}else{return{x:e.touches[0].pageX,y:e.touches[0].pageY};}},click:function(e){var event=e.originalEvent;if(this.moved){event.stopPropagation();}},touchstart:function(e){var event=e.originalEvent;if(this.gesturing){event.preventDefault();return false;}
this.setDefaults(e);if(true===this.msTouch){this.$target[0].msSetPointerCapture(event.pointerId);}
$(window).bind('gesturestart',$.proxy(this.gesturestart,this));$(window).bind('gestureend',$.proxy(this.gestureend,this));this.fingerCount++;this.trigger('touchstart',event);},touchmove:function(e){var event=e.originalEvent;if(this.gesturing){return false;}
this.offset.x=this.getPosition(event).x-this.startPosition.x;this.offset.y=this.getPosition(event).y-this.startPosition.y;if(this.offset.x===0&&this.offset.y===0){return false;}
this.moved=true;this.lastMoveTime=new Date();this.lastPosition=this.currentPosition;this.currentPosition=this.getPosition(event);if(false===this.direction){if(Math.abs(this.offset.x)>15&&Math.abs(this.offset.x)>Math.abs(this.offset.y)){this.direction='horizontal';}else if(Math.abs(this.offset.y)>15&&Math.abs(this.offset.y)>Math.abs(this.offset.x)){this.direction='vertical';}}
this.trigger('touchmove',event);},touchend:function(e){var event=e.originalEvent;this.fingerCount--;$(window).unbind('gesturestart');$(window).unbind('gestureend');if(true===this.msTouch){this.$target[0].msReleasePointerCapture(e.pointerId);}
if(false===this.moved){this.tap(event);}
if(this.direction==='horizontal'){if(this.offset.x>0){this.trigger('swiperight',e);}
if(this.offset.x<0){this.trigger('swipeleft',e);}}
if(this.direction==='vertical'){if(this.offset.y>0){this.trigger('swipedown',e);}
if(this.offset.y<0){this.trigger('swipeup',e);}}
this.trigger('touchend',event);},tap:function(e){if((new Date()-this.latestTap)>400){this.trigger('tap',e);}else{this.trigger('doubletap',e);}
this.latestTap=new Date();},gesturestart:function(e){this.fingerCount++;this.trigger('gesturestart',e);this.gesturing=true;},gestureend:function(e){this.fingerCount--;this.trigger('gestureend',e);this.gesturing=false;},isTossed:function(){if(Math.abs(this.tossOffset().x)>Math.abs(this.currentPosition.x)+100){return true;}
return false;},tossOffset:function(){var x,dx;if(this.offset.x>0){x=this.currentPosition.x;dx=this.currentPosition.x-this.lastPosition.x;}else if(this.offset.x<0){x=this.lastPosition.x;dx=this.lastPosition.x-this.currentPosition.x;}
var dt=(new Date())-this.lastMoveTime+1;var tossedX=x+dx*100/dt;tossedX=this.offset.x>0?tossedX:-tossedX;return{"x":tossedX};},trigger:function(type,e){virb.log(type);this.$target.trigger('touch',{currentPosition:this.currentPosition,currentTarget:this.$target[0],direction:this.direction,event:e,eventType:type,msTouch:this.msTouch,fingerCount:this.fingerCount,isTossed:this.isTossed(),tossOffset:this.tossOffset(),offset:this.offset,startPosition:this.startPosition});}};})();;"use strict";var HashManager;(function(){var $doc=$(document),$window=$(window),$html=$('html'),$body=$('body');virb.gallery={getDefaultMobileQueue:function(){var defaultQueue='thumbs';if(this.args.format==='horizontal'||this.args.format==='vertical'){defaultQueue='images';}
if(this.args.format==='horizontal'&&virb.site.config.reverseMobileQueue&&virb.site.config.isMobile){defaultQueue=defaultQueue==='thumbs'?'images':'thumbs';}
if(this.args.format==='grid'&&virb.site.config.isMobile){defaultQueue='images';}
return defaultQueue;},init:function(){if(virb.site.config.autoresize&&!virb.site.config.isMobile){$(virb.site.config.autoresize).autoResizer();}
this.initArgs();this.initObjs();if(this.args.hasLightbox){this.objs.lightbox=Lightbox;this.objs.lightbox.init(this);}
if(this.args.hasAutoplay){this.objs.autoplay=AutoPlay;this.objs.autoplay.init(this);}
HashManager.init();this.attachEvents();this.showCurrentView();},initArgs:function(){this.args={firstView:true,previousView:false,isMobile:virb.site.config.isMobile,format:virb.site.config.gallery.format,startOn:virb.site.config.gallery.startOn,isSlideshow:false,hasAutoplay:virb.site.config.isMobile?false:virb.site.config.gallery.autoplay,autoplayDelay:virb.site.config.gallery.autoplay_delay,hasThumbs:false,hasLightbox:false,};if(virb.site.config.gallery.format==='slideshow_thumbnails'){this.args.hasThumbs=true;}
if(virb.site.config.gallery.lightbox){this.args.hasLightbox=true;}
if(virb.site.config.gallery.format==='slideshow'||virb.site.config.gallery.format==='slideshow_thumbnails'){this.args.isSlideshow=true;if(virb.site.config.isTouch){this.args.hasLightbox=true;}}
if(this.getDefaultMobileQueue()==='thumbs'&&virb.site.config.forceMobileLightbox){this.args.hasLightbox=true;}
virb.log(virb.site.config);virb.log(this.args);},initObjs:function(){var selector=false;switch(this.args.format){case"slideshow":selector='section.slideshow-gallery';break;case"slideshow_thumbnails":selector='section.slideshow-thumbnails-gallery';break;case"vertical":selector='section.vertical-gallery';break;case"horizontal":selector='section.horizontal-gallery';break;case"grid":selector='section.grid-gallery';break;}
var gallery=$(selector);var images=gallery.find('.large-gallery');var thumbs=gallery.find('.thumbnails');var galleryList=images;if(!galleryList.is('ul')){galleryList=galleryList.find('ul');}
galleryList.css({position:'relative'});this.objs={gallery:gallery,images:images,thumbs:thumbs,thumbImages:thumbs.find('img'),thumbItems:thumbs.children('li'),galleryList:galleryList,galleryItems:images.children('li'),galleryImages:images.find('img'),previousButton:gallery.find('.navigation .previous'),nextButton:gallery.find('.navigation .next'),currentCount:gallery.find('.navigation .count .current'),imageQueue:{thumbs:{paused:false,loaded:false,maxQueue:20,queued:0,loadedQueue:[]},images:{paused:false,loaded:false,maxQueue:5,queued:0,loadedQueue:[]},lightbox:{queue:[],paused:false,loaded:false,maxQueue:this.args.isMobile?1:3,queued:0,loadedQueue:[]}}};if(this.args.format==='slideshow'||this.args.format==='slideshow_thumbnails'){this.objs.galleryItems=images.children('ul').children('li');}
this.objs.imageQueue.thumbs.queue=this.objs.thumbImages;this.objs.imageQueue.images.queue=this.objs.galleryImages;this.objs.currentItem=this.objs.galleryItems.eq(0);$.event.trigger('initObjs.gallery.virb');},attachEvents:function(){var self=this;$body.bind('loaded.image.gallery.virb',function(e,$image,status){self.imageLoaded($image,status);});$body.bind('complete.queue.gallery.virb',function(e,type){if(!self.args.isMobile){self.startNextQueue(type);}});$body.bind('arrowLeft.virb',$.proxy(this.moveToPrevious,this));$body.bind('arrowRight.virb',$.proxy(this.moveToNext,this));$body.bind('escape.virb',$.proxy(this.handleEscape,this));$body.bind('hashChange.gallery.virb',function(){self.args.firstView=false;self.showCurrentView();});this.objs.previousButton.click($.proxy(this.moveToPrevious,this));this.objs.nextButton.click($.proxy(this.moveToNext,this));this.objs.thumbItems.find('a').bind('click',function(e){self.handleThumbClick($(this));e.preventDefault();});this.objs.galleryImages.bind('click',function(e){self.handleImageClick(e,$(this));});this.attachKeyEvents();},attachKeyEvents:function(){if(this.args.hasAutoplay){return;}
$(window).keydown(function(e){var code=e.keyCode||e.which;switch(code){case 37:$.event.trigger('arrowLeft.virb');break;case 39:$.event.trigger('arrowRight.virb');break;case 27:$.event.trigger('escape.virb');e.preventDefault();break;}});},manageProgression:function(e){if(this.objs.currentItem.hasClass('transitioning')){if(e){e.preventDefault();return;}}
if(this.args.hasAutoplay){if(e){if(false!==this.objs.autoplay.transitionInterval){this.objs.autoplay.stop();}}}},moveToNext:function(e){if(this.args.format==='vertical'&&this.getCurrentView()!=='lightbox'){return;}
var currentIndex=this.objs.currentItem.index();var nextIndex=currentIndex+1;var $nextItem=this.objs.galleryItems.eq(nextIndex);this.manageProgression(e);if(!$nextItem.length){$nextItem=this.objs.galleryItems.eq(0);}
if(this.getCurrentView()==='lightbox'&&$nextItem.data('type')==='video'&&false===this.args.isMobile){this.objs.currentItem=$nextItem;this.moveToNext();return;}
this.moveToItem($nextItem);if(e){e.preventDefault();}},moveToPrevious:function(e){if(this.args.format==='vertical'&&this.getCurrentView()!=='lightbox'){return;}
var currentIndex=this.objs.currentItem.index();var nextIndex=currentIndex-1;var $nextItem=this.objs.galleryItems.eq(nextIndex);this.manageProgression(e);if(!$nextItem.length){$nextItem=this.objs.galleryItems.last();}
if(this.getCurrentView()==='lightbox'&&$nextItem.data('type')==='video'&&false===this.args.isMobile){this.objs.currentItem=$nextItem;this.moveToPrevious();return;}
this.moveToItem($nextItem);if(e){e.preventDefault();}},moveToItem:function($item){this.pauseVideoPlayback();var hashParts=['id',$item.data('id')];if(this.getCurrentView()==='lightbox'){hashParts.push('full');}
HashManager.setHash(hashParts);},pauseVideoPlayback:function(){var playingVideos=$('.large-gallery ul li .video-js');var videoId=0;if(playingVideos.length>0){for(var i=0;i<playingVideos.length;i++){videoId=playingVideos[i].getAttribute('id');var videoJSInstance=videojs(videoId);videoJSInstance.pause();}}},handleEscape:function(){var currentView=this.getCurrentView();var hashParts=[' '];if(currentView==='lightbox'&&this.args.format!=='vertical'){var $item=this.getItemByHash();hashParts=['id',$item.data('id')];}
HashManager.setHash(hashParts);},handleThumbClick:function($thumb){virb.log('clicked thumb');var $item=this.getItemByImage($thumb),hashParts=['id',$item.data('id')],$link='';if(this.args.hasAutoplay){return;}
if(this.args.isMobile){if(this.args.format==='slideshow'||this.args.format==='slideshow_thumbnails'){hashParts.push('full');HashManager.setHash(hashParts);}else{$link=$item.find('.media-container > a').attr('href');if(virb.site.config.forceMobileLightbox){if($link!==''&&$link!==undefined){window.location.href=$link;return;}}
if(this.args.hasLightbox){hashParts.push('full');HashManager.setHash(hashParts);return;}
if($link!==''&&$link!==undefined){window.location.href=$link;}
return;}}else{HashManager.setHash(hashParts);}},handleImageClick:function(e,$image){virb.log('clicked image');var $item=this.getItemByImage($image),index=$item.index(),$link='',$thumb=this.objs.thumbs.find('li:eq('+index+') a');e.preventDefault();if(this.args.format==='horizontal'){$link=$item.find('.media-container > a');}else{$link=$item.find('> a');}
if(this.args.hasLightbox){var hashParts=['id',$item.data('id'),'full'];HashManager.setHash(hashParts);e.preventDefault();return;}
if(this.args.isSlideshow&&$thumb.attr('href')!==''){window.location.href=$thumb.attr('href');return;}else if(this.args.format==='horizontal'&&$link.length&&$link.attr('href')!==''){window.location.href=$link.attr('href');return;}else if(this.args.format==='vertical'&&$link.length&&$link.attr('href')!==''){window.location.href=$link.attr('href');return;}
this.moveToNext(e);},runQueue:function(type){console.log('running queue '+type);if(!type){type=this.getCurrentView();}
if(this.objs.imageQueue[type].paused){return;}
var currentQueueLength=this.objs.imageQueue[type].queue.length,loadedQueueLength=this.objs.imageQueue[type].loadedQueue.length;while(loadedQueueLength<currentQueueLength){this.loadNextImage(type);loadedQueueLength++;}
if(this.args.format==='slideshow_thumbnails'&&virb.site.config.forceThumbQueue){this.startNextQueue('images');}},startNextQueue:function(prevType){console.log("startNextQueue");var nextType=this.getNextQueue(prevType);if(this.objs.imageQueue[nextType].queue.length>0){this.unpauseQueue(nextType);this.runQueue(nextType);return;}
prevType=nextType;nextType=this.getNextQueue(prevType);if(this.objs.imageQueue[nextType].queue.length>0){this.unpauseQueue(nextType);this.runQueue(nextType);return;}},getNextQueue:function(prevType){if(this.args.isMobile){if(this.args.isSlideshow){if(prevType==='thumbs'){}
return'thumbs';}
if(prevType==='images'||prevType==='thumbs'){}
return this.getDefaultMobileQueue();}
if(this.args.format==='horizontal'){if(prevType==='images'){}else if(virb.site.config.hasHorizontalThumbs&&prevType==='lightbox'){return'thumbs';}
return'images';}else if(this.args.format==='vertical'){if(prevType==='images'){}
return'images';}
if(this.args.startOn==='thumbs'){if(prevType==='images'){}else if(prevType==='lightbox'){return'thumbs';}
return'images';}
if(this.args.format==='slideshow'){if(prevType==='images'){}else if(prevType==='lightbox'){return'thumbs';}
return'images';}
if(prevType==='images'){return'thumbs';}else if(prevType==='thumbs'){}
return'images';},maxQueue:function(type){return this.objs.imageQueue[type].maxQueue;},currentQueue:function(type){return this.objs.imageQueue[type].queued;},pauseQueue:function(type){this.objs.imageQueue[type].paused=true;},unpauseQueue:function(type){this.objs.imageQueue[type].paused=false;},loadImage:function($image,type){console.log('loading '+type+" "+$image);if($image.prop('src')===$image.data('src')){$.event.trigger('loading.image.gallery.virb',[$image]);return false;}
if(type==='thumbs'){this.attachFader($image);}
$image.data('type',type);var $clone=$image.clone(true);$image.replaceWith($clone);var src=$clone.data('src');if(this.args.isMobile&&type==='images'){src=src.replace('resize_800x800','resize_500x500');}
$clone.prop('src',src);if($clone.get(0).complete){$.event.trigger('loaded.image.gallery.virb',[$clone,'ok']);}else{$clone.load(function(){$.event.trigger('loaded.image.gallery.virb',[$(this),'ok']);}).error(function(){$.event.trigger('loaded.image.gallery.virb',[$(this),'error']);});}
$.event.trigger('loading.image.gallery.virb',[$clone]);return $clone;},loadImageByItem:function($item,type){var $image=$item.find('img');return this.loadImage($image,type);},imageLoaded:function($image,status){var type=$image.data('type');this.objs.imageQueue[type].queued--;if(this.objs.imageQueue[type].queued===0&&this.objs.imageQueue[type].queue.length===0){$.event.trigger('complete.queue.gallery.virb',[type]);}else if(false===this.objs.imageQueue[type].paused){this.loadNextImage(type);}
if(status==='ok'){$image.css({height:'',width:''});if(type==='thumbs'){$image.animate({'opacity':1},function(){$(this).css('opacity','');});}}else{$image.css({height:'',width:''}).hide();}
this.objs.imageQueue[type].loadedQueue.push($image);},loadNextImage:function(type){var $image=this.objs.imageQueue[type].queue.shift();if((this.objs.gallery.hasClass('vertical-layout')||virb.site.config.isMobile)&&$image.hasClass('square-thumb')){return false;}else if(!this.objs.gallery.hasClass('vertical-layout')&&!virb.site.config.isMobile&&$image.hasClass('vertical-thumb')){return false;}
this.loadImage($image,type);},getCurrentView:function(){var hashParts=HashManager.parseHash();var currentView='images';var item=false;if(this.args.isMobile){currentView=this.getDefaultMobileQueue();}
else if(this.args.firstView&&this.args.hasThumbs&&this.args.startOn==='thumbs'){currentView='thumbs';}else if(!this.args.firstView&&this.args.hasThumbs){currentView='thumbs';}
if(!hashParts[1]){return currentView;}
if(hashParts[1]==='id'&&hashParts[2]){item=this.objs.galleryItems.filter('[data-id="'+hashParts[2]+'"]');}else if(hashParts[1]==='i'&&hashParts[2]){item=this.objs.galleryItems.eq(hashParts[2]);}
if(!item||item.length<=0){return currentView;}
if(hashParts[3]!==undefined&&hashParts[3]==='full'&&this.args.hasLightbox){currentView='lightbox';}else if(this.args.isMobile){currentView=this.getDefaultMobileQueue();}else{currentView='images';}
return currentView;},showCurrentView:function(){var currentView=this.getCurrentView();virb.log('showCurrentView('+currentView+')');if(this.args.previousView===false){this.args.previousView=currentView;}
if(currentView!==this.args.previousView||this.args.firstView){if(currentView==='images'){this.showImages();}else if(currentView==='thumbs'){this.showThumbnails();}else if(currentView==='lightbox'){this.objs.lightbox.show();}
$.event.trigger(currentView+'.show.gallery.virb');}
if(this.args.format==='horizontal'&&virb.site.config.reverseMobileQueue&&!virb.site.config.isMobile&&currentView!=='lightbox'){this.showThumbnails();}
if(currentView==='images'&&this.args.isSlideshow){this.showCurrentItem();}else if(currentView==='lightbox'){this.objs.lightbox.showCurrentItem();}
this.args.previousView=currentView;},showCurrentItem:function(){var $item=this.getItemByHash();this.objs.galleryItems.hide();this.loadImageByItem($item,'images');if(this.args.hasAutoplay){$item.addClass('transitioning fade-in').fadeIn('fast',function(){$(this).removeClass('transitioning fade-in');});if($item.get(0)!==this.objs.currentItem.get(0)){this.objs.currentItem.addClass('transitioning fade-out').fadeOut('fast',function(){$(this).removeClass('transitioning fade-out');});}}else{$item.css({left:'auto'}).hide().show();$item.siblings().css({left:'auto'}).hide();}
this.objs.currentCount.html($item.index()+1);this.objs.currentItem=$item;$.event.trigger('show_item_image.gallery.virb',[$item.find('img')]);},getItemByImage:function($image){var index=$image.closest('li').index();var $item=this.objs.galleryItems.eq(index);return $item;},getItemByHash:function(type){if(!type){var type='images';}
var hashParts=HashManager.parseHash();var $items=type==='images'?this.objs.galleryItems:this.objs.lightbox.objs.listItems;var $defaultItem=$items.eq(0);var $item=false;if(!hashParts[1]){return $defaultItem;}
if(hashParts[1]==='id'&&hashParts[2]){$item=$items.filter('[data-id="'+hashParts[2]+'"]');}else if(hashParts[1]==='i'&&hashParts[2]){$item=$items.eq(hashParts[2]);}
if(!$item||$item.length<=0){return $defaultItem;}
return $item;},setItemByHash:function(type){this.objs.currentItem=this.getItemByHash(type);},showThumbnails:function(){this.objs.gallery.removeClass('show');if(this.args.hasLightbox){this.objs.lightbox.hide();}
this.pauseQueue('lightbox');this.pauseQueue('images');this.unpauseQueue('thumbs');this.runQueue('thumbs');},showImages:function(){this.objs.gallery.addClass('show');if(this.args.hasLightbox){this.objs.lightbox.hide();}
this.pauseQueue('lightbox');this.pauseQueue('thumbs');this.unpauseQueue('images');if(this.objs.imageQueue.images.queue.length===0){$.event.trigger('complete.queue.gallery.virb',['images']);return;}
this.runQueue('images');},attachFader:function($image){if(this.args.isMobile){return false;}
if($image.prop('src')!==$image.data('src')){$image.css({opacity:0});this.setImageDimensions($image);}},setImageDimensions:function($image){var heightWidth=aspectRatio($image.data('width'),$image.data('height'),{'targetWidth':$image.width()});if(heightWidth.width>0&&heightWidth.height>0){$image.css({height:heightWidth.height,width:heightWidth.width});}}};HashManager={current:false,init:function(){var self=this;$(window).bind('hashchange',function(){self.hashListener();});},hashListener:function(){var old=this.current,scrollLoc=$(document).scrollTop();this.current=this.getHash();if(old!==this.current){$.event.trigger('hashChange.gallery.virb');}
$(document).scrollTop(scrollLoc);},parseHash:function(){var hash=this.getHash();return hash.split('/');},getHash:function(){var hash=window.location.hash;try{hash=window.parent.virb.$.customize.customizeHash;}catch(e){}
return hash;},setHash:function(parts){var hash=parts.join('/');if(hash!==''){hash='/'+hash;}
try{window.parent.$.customize.customizeHash='#'+hash;}catch(e){window.location.hash=hash;}
this.hashListener();},emptyHash:function(){try{window.parent.$.customize.customizeHash='';}catch(e){window.location.hash='';}
this.hashListener();}};var AutoPlay={transitionInterval:false,init:function(gallery){var self=this;this.gallery=gallery;$window.on('beforeunload',function(){self.stop();});this.start();},stop:function(){window.clearInterval(this.transitionInterval);this.transitionInterval=false;},start:function(){var self=this;if(!this.transitionInterval){this.transitionInterval=setInterval(function(){self.transition();},this.gallery.args.autoplayDelay);}},transition:function(){this.gallery.moveToNext();}};var Lightbox={uiTimeout:1000,timeout:false,init:function(gallery){this.gallery=gallery;this.build();this.attachCss();this.attachEvents();},attachCss:function(){if(document.createStyleSheet){document.createStyleSheet("http://"+virb.site.config.virbCDNDomain+"/_assets/_themes/fullscreen.css");}
$('head').append('<link rel="stylesheet" href="http://'+virb.site.config.virbCDNDomain+'/_assets/_themes/fullscreen.css" />');},attachEvents:function(){if(false===virb.site.config.isTouch){this.objs.previousButton.click($.proxy(this.gallery.moveToPrevious,this.gallery));this.objs.nextButton.click($.proxy(this.gallery.moveToNext,this.gallery));}
if(virb.site.config.isTouch&&false===virb.site.config.msTouch){this.objs.close.bind('touchstart',$.proxy(this.hideTimeout,this));}else{this.objs.close.click($.proxy(this.hideTimeout,this));}
if(virb.site.config.isTouch){TouchManager.init(this.objs.fullscreen);}},build:function(){var self=this,container=$('<div>',{id:'fullscreen',style:'display: none;'}),inner=$('<div>',{id:'fullscreen_slideshow'});container.append(inner);var prev=$('<a>',{'class':'button prev','data-icon':'‹'}).fixIcons(),next=$('<a>',{'class':'button next after','data-icon':'›'}).fixIcons(),close=$('<a>',{'class':'button close','data-icon':'×'}).fixIcons(),currentPosition=$('<span>',{id:'current_index'}).append(),controls=$('<div>',{id:'controls'}),closeBanner=$('<div>',{id:'close-banner'});closeBanner.append(close);controls.prepend(next).prepend(prev);inner.prepend(closeBanner).append(controls);var list=$('<ul>',{id:'fullscreen_media'});this.gallery.objs.galleryItems.each(function(){var clone=$(this).clone();clone.hide();var img=clone.find('img');if(virb.site.config.isTouch){img.parent('a').replaceWith(img);}
img.data('src',img.data('full-src'));clone.on('click',function(e){if(false===virb.site.config.isTouch){self.gallery.moveToNext();}
e.preventDefault();});list.append(clone);});inner.append(list);var listItemCollection=list.find('li[data-type]');listItemCollection.each(function(){if($(this).data('type')==='video'){var video=$(this).find('.video>div');var flashObject=video.find('object');var videoId=video.attr('id')+'_full';var flashId=flashObject.attr('id')+'_full';video.attr('id',videoId);flashObject.attr('id',flashId);}});this.objs={fullscreen:container,list:list,listItems:listItemCollection,listImages:list.find('img'),previousButton:prev,nextButton:next,close:close,closeBanner:closeBanner,controls:controls,currentPosition:currentPosition};this.gallery.objs.imageQueue.lightbox.queue=this.objs.listImages;$body.prepend(this.objs.fullscreen);},show:function(){if(this.gallery.args.hasAutoplay){this.gallery.objs.autoplay.stop();}
this.gallery.pauseQueue('thumbs');this.gallery.pauseQueue('images');this.gallery.unpauseQueue('lightbox');this.gallery.runQueue('lightbox');this.showCurrentItem();var self=this;var currentIndex=this.gallery.objs.currentItem.index();var currentItem=this.objs.listItems.eq(currentIndex);var currentImage=currentItem.find('img');this.adjustOffsets();$html.addClass('fullscreen');if(virb.site.config.msTouch){var galleryOffset=1*$window.width()*currentIndex;currentItem.css({'left':galleryOffset});}
this.objs.fullscreen.fadeIn('fast',function(){if(virb.site.config.isTouch){currentImage.css({width:currentImage.width()});setTimeout(function(){currentImage.css({width:'auto'});},100);}});if(virb.site.config.isWindowsPhone7){$doc.scrollTop(0);$html.addClass('windows-phone-7');}
if(virb.site.config.isTouch){$doc.bind('touchmove',this.preventOriginalEvent);$window.bind('orientationchange',function(){self.orientationchange();});}else{$doc.bind('mousemove',$.proxy(this.showUI,this));this.showUI();}},orientationchange:function(){var currentIndex=this.gallery.objs.currentItem.index();var currentItem=this.objs.listItems.eq(currentIndex);var currentImage=currentItem.find('img');currentImage.css({width:currentImage.width()});setTimeout(function(){currentImage.css({width:'auto'});},1);this.adjustOffsets();},adjustOffsets:function(){var currentIndex=this.gallery.objs.currentItem.index();var galleryOffset=1*$window.width()*currentIndex;if(virb.site.config.msTouch){this.objs.list.css({'left':-galleryOffset});}else if(virb.site.config.isTouch){this.objs.list.css({'-webkit-transition':'-webkit-transform 0ms','-webkit-transform':'translate3d('+-galleryOffset+'px, 0, 0)'});this.objs.listItems.each(function(i){$(this).css({'left':1*$window.width()*i});});}},hide:function(args){var self=this;var winHeight=$window.height();if(this.gallery.args.hasAutoplay){this.gallery.objs.autoplay.start();}
if(!this.objs.fullscreen.is(':visible')){return;}
$html.removeClass('fullscreen').removeClass('windows-phone-7');if(args&&args.noFade){this.objs.fullscreen.hide();}
else if(virb.site.config.isTouch&&true===TouchManager.msTouch){this.objs.fullscreen.animate({top:(winHeight+100)},"fast",function(){self.objs.fullscreen.hide({noFade:true});$(this).css({top:0});});}else if(virb.site.config.isTouch){this.objs.fullscreen.css({'-webkit-transition-duration':'.5s','-webkit-transform':'translate3d(0, '+(winHeight+100)+'px, 0)'}).bind('webkitTransitionEnd',function(){self.objs.fullscreen.hide();$(this).css({'-webkit-transition-duration':'0s','-webkit-transform':'translate3d(0, 0, 0)'}).unbind('webkitTransitionEnd');});}else{this.objs.fullscreen.fadeOut('fast');}
this.hideUI();if(virb.site.config.isTouch){$doc.unbind('touchmove',this.preventOriginalEvent);}else{$doc.unbind('mousemove',$.proxy(this.showUI,this));}},hideTimeout:function(e){clearTimeout(this.timeout);var hashParts=HashManager.parseHash();hashParts.shift();hashParts.pop();HashManager.setHash(hashParts);e.preventDefault();},showUI:function(e){if(false===virb.site.config.isTouch){clearTimeout(this.timeout);if(false===virb.site.config.isWindowsPhone7&&typeof e!=='undefined'&&false===$(e.target).hasClass('button')){this.timeout=setTimeout($.proxy(this.hideUI,this),this.uiTimeout);}
if(false===this.objs.controls.is(':animated')){this.objs.controls.animate({opacity:1},'fast');}}
if(false===this.objs.closeBanner.is(':animated')){this.objs.closeBanner.animate({opacity:1},'fast');}},hideUI:function(){if(false===virb.site.config.isTouch){this.objs.controls.stop().animate({opacity:0},'fast');}
this.objs.closeBanner.stop().animate({opacity:0},'fast');},toggleUI:function(){if(this.objs.closeBanner.css('opacity')>0){this.hideUI();}else{this.showUI();}},showCurrentItem:function(){var $item=this.gallery.getItemByHash('lightbox');this.gallery.loadImageByItem($item,'lightbox');$item.show();$item.siblings().hide();this.gallery.objs.currentItem=$item;$.event.trigger('show_item_image.gallery.virb',[$item.find('img')]);},preventOriginalEvent:function(e){e.originalEvent.preventDefault();}};var TouchManager={msTouch:false,init:function(touchTarget){this.touchTarget=touchTarget;var self=this;touchTarget.addTouch(function(e,touch){if(true===touch.msTouch){self.msTouch=true;}
self.touching(e,touch);});},touching:function(e,touch){if(touch.fingerCount>1){return false;}
if(typeof this.touchTarget.data('isTransitioning')!=='undefined'&&true===this.touchTarget.data('isTransitioning')){return false;}
var currentIndex=virb.gallery.objs.currentItem.index();if(currentIndex!==this.touchTarget.data('currentIndex')){this.winWidth=$window.width();this.winHeight=$window.height();var nextIndex=(currentIndex+1)>Lightbox.objs.listItems.length-1?false:(currentIndex+1);var prevIndex=(currentIndex-1)<0?false:(currentIndex-1);this.touchTarget.data({'currentIndex':currentIndex,'nextImage':false,'currentImage':Lightbox.objs.listItems.eq(currentIndex),'prevImage':false,'startOffset':-this.winWidth*currentIndex});if(typeof this.touchTarget.data('isTransitioning')==='undefined'){this.touchTarget.data({'isTransitioning':false});}
if(false!==nextIndex){this.touchTarget.data({'nextIndex':nextIndex});this.touchTarget.data({'nextImage':Lightbox.objs.listItems.eq(nextIndex)});this.touchTarget.data('nextImage').css({left:this.winWidth*nextIndex}).show();}
if(false!==prevIndex){this.touchTarget.data({'prevIndex':prevIndex});this.touchTarget.data({'prevImage':Lightbox.objs.listItems.eq(prevIndex)});this.touchTarget.data('prevImage').css({left:this.winWidth*prevIndex}).show();}}
switch(touch.eventType){case"touchmove":this.touchmove(e,touch);break;case"swipedown":this.swipedown(e,touch);break;case"tap":Lightbox.toggleUI();break;case"swipeleft":this.swipeleft(e,touch);break;case"swiperight":this.swiperight(e,touch);break;}},touchmove:function(e,touch){if(touch.direction==='horizontal'){if(true===touch.msTouch){Lightbox.objs.list.css({left:1*touch.offset.x+this.touchTarget.data('startOffset')});}else{Lightbox.objs.list.css({'-webkit-transition-duration':'0s'});Lightbox.objs.list.css({'-webkit-transform':'translate3d('+(1*touch.offset.x+this.touchTarget.data('startOffset'))+'px, 0, 0)'});}}},swipedown:function(e){Lightbox.hideTimeout(e);},swipeleft:function(e,touch){var self=this;if(true===this.touchTarget.data('isTransitioning')){return false;}
this.touchTarget.data({'isTransitioning':true});if((-touch.offset.x>this.winWidth*0.50||touch.isTossed)&&false!==this.touchTarget.data('nextImage')){if(true===touch.msTouch){Lightbox.objs.list.animate({left:-self.winWidth*self.touchTarget.data('nextIndex')},'fast',function(){if(false!==self.touchTarget.data('prevImage')){self.touchTarget.data('prevImage').hide();}
virb.gallery.moveToNext();self.touchTarget.data({'isTransitioning':false});});}else{Lightbox.objs.list.bind('webkitTransitionEnd',function(){if(false!==self.touchTarget.data('prevImage')){self.touchTarget.data('prevImage').hide();}
virb.gallery.moveToNext();self.touchTarget.data({'isTransitioning':false});$(this).unbind('webkitTransitionEnd');}).css({'-webkit-transition-duration':'.3s','-webkit-transform':'translate3d('+-self.winWidth*self.touchTarget.data('nextIndex')+'px, 0, 0)'});}}else{this.reset(touch,'.3s');}},swiperight:function(e,touch){var self=this;if(true===this.touchTarget.data('isTransitioning')){return false;}
this.touchTarget.data({'isTransitioning':true});if((touch.offset.x>this.winWidth*0.50||touch.isTossed)&&false!==this.touchTarget.data('prevImage')){if(true===touch.msTouch){Lightbox.objs.list.animate({left:-1*self.winWidth*self.touchTarget.data('prevIndex')},'fast',function(){if(false!==self.touchTarget.data('nextImage')){self.touchTarget.data('nextImage').hide();}
virb.gallery.moveToPrevious();self.touchTarget.data({'isTransitioning':false});});}else{Lightbox.objs.list.css({'-webkit-transition-duration':'.3s','-webkit-transform':'translate3d('+-1*self.winWidth*self.touchTarget.data('prevIndex')+'px, 0, 0)'}).bind('webkitTransitionEnd',function(){if(false!==self.touchTarget.data('nextImage')){self.touchTarget.data('nextImage').hide();}
virb.gallery.moveToPrevious();$(this).unbind('webkitTransitionEnd');self.touchTarget.data({'isTransitioning':false});});}}else{this.reset(touch,'.3s');}},reset:function(touch,speed){var self=this;if(true===touch.msTouch){Lightbox.objs.list.animate({left:-1*self.winWidth*self.touchTarget.data('currentIndex')},'fast',function(){self.touchTarget.data({'isTransitioning':false});});}else{Lightbox.objs.list.bind('webkitTransitionEnd',function(){self.touchTarget.data({'isTransitioning':false});$(this).unbind('webkitTransitionEnd');}).css({'-webkit-transition-duration':speed,'-webkit-transform':'translate3d('+(-1*self.winWidth*self.touchTarget.data('currentIndex'))+'px, 0, 0)'});}}};var AutoResizer=function(element,args){if(virb.site.config.isMobile){return false;}
this.objs={};this.objs.gallery=$(element);this.args={'minHeight':400};var self=this;if(args){$.each(args,function(key,value){self.args[key]=value;});}
$body.bind('show_item_image.gallery.virb',function(){self.adjustSizes();});$body.bind('loading.image.gallery.virb',function(e,$image){if($image.data('type')==='images'){self.adjustSize($image);}});$body.bind('embedswf.video.virb',function(e,$video){self.adjustSize($video);});$body.bind('initObjs.gallery.virb',function(){self.adjustVideoSizes();});$window.resize(function(){self.adjustSizes();});};AutoResizer.prototype={constructor:AutoResizer,setViewableArea:function(){var offsetTop=virb.gallery.objs.galleryList.offset().top;var windowHeight=$(window).height();this.viewableArea={height:windowHeight-offsetTop,width:virb.gallery.objs.galleryList.width()};},adjustSizes:function(){virb.log('adjustSizes');this.setViewableArea();this.adjustImageSizes();},adjustVideoSizes:function(){var self=this;virb.gallery.objs.galleryList.find('object,iframe,embed,video').each(function(){self.adjustSize($(this));});},adjustImageSizes:function(){var self=this;$.each(virb.gallery.objs.imageQueue.images.loadedQueue,function(){self.adjustSize($(this));});$.event.trigger('resize.slider.virb');},adjustSize:function($media){this.setViewableArea();if($media.data('type')!=='images'){return;}
var mediaWidth=$media.data('width');var mediaHeight=$media.data('height');if($media.data('original-height')===undefined){$media.data('original-height',mediaHeight);}
var originalWidth=mediaWidth,originalHeight=mediaHeight;if(false===mediaWidth&&false===mediaHeight){originalWidth=$media.attr('width');originalHeight=$media.attr('height');}
var widthRatio=this.viewableArea.width/originalWidth,heightRatio=this.viewableArea.height/originalHeight,targetHeight=originalHeight*heightRatio,targetWidth=originalWidth*heightRatio;if((virb.gallery.objs.gallery.hasClass('slideshow-gallery')||virb.gallery.objs.gallery.hasClass('slideshow-thumbnails-gallery'))&&targetWidth>this.viewableArea.width){targetHeight=originalHeight*widthRatio;}
targetHeight-=50;if(targetHeight>originalHeight&&$media.prop('tagName')==='IMG'){targetHeight=originalHeight;}
var cssSettings={'max-height':targetHeight,'height':targetHeight,'max-width':'','width':''};if(targetHeight<this.args.minHeight){targetHeight=this.args.minHeight;targetWidth=targetHeight/originalHeight*originalWidth;cssSettings['max-height']='';cssSettings.height='';}
$media.css(cssSettings);if($media.prop('tagName')!=='IMG'){targetWidth=originalWidth*targetHeight/originalHeight;$media.css({'height':targetHeight}).parent().css({'width':targetWidth});}}};$.fn.autoResizer=function(args){return this.each(function(){new AutoResizer(this,args);});};$.fn.unshift=function($item){return this.push($item);};$.fn.shift=function(){var bottom=this.first();this.splice(0,1);return bottom;};$(function(){virb.gallery.init();});})();;(function(){var $body=$('body');var Slider=function(element){this.objs={dims:{maxLeft:0}};this.objs.element=$(element);this.objs.items=this.objs.element.find('li');this.objs.element.css({overflow:'visible',position:'relative',left:0});this.buildSlider();this.objs.element.after(this.objs.slider);this.attachEvents();var self=this;this.updateInterval=setInterval(function(){self.updateDimensions();},2000);};Slider.prototype={constructor:Slider,attachEvents:function(){var self=this;this.objs.element.on('mousewheel',$.proxy(this.scroll,this));this.objs.handle.disableSelection();this.objs.handle.on('mousedown',$.proxy(this.dragStart,this));this.objs.handle.on('touchstart',$.proxy(this.dragStart,this));this.objs.track.click($.proxy(this.seek,this));$body.bind('resize.slider.virb',$.proxy(this.updateDimensions,this));$body.bind('loaded.image.gallery.virb',$.proxy(this.updateDimensions,this));$body.bind('complete.queue.gallery.virb',function(e,type){if(type==='images'){virb.log('clearing loading interval');clearInterval(self.updateInterval);delete(self.updateInterval);}});$body.bind('hashChange.gallery.virb',function(){self.updatePositionFromHash();});if(virb.site.config.isTouch){this.objs.element.addTouch(function(e,touch){self.touchScroll(e,touch);});}},buildSlider:function(){this.objs.slider=$('<div>',{'id':'slider','class':'slider-track'});this.objs.track=$('<div>',{'class':'slider-track-x'});this.objs.handle=$('<div>',{'id':'handle','class':'slider-drag'}).css({'position':'relative','left':0});this.objs.slider.bind('selectstart',function(){return false;});this.objs.slider.append(this.objs.track.append(this.objs.handle));},updateDimensions:function(){if(this.objs.dims===undefined){this.objs.dims={};}
var contentWidth=0;this.objs.element.find('li').each(function(){contentWidth+=$(this).outerWidth();});this.objs.dims.containerWidth=this.objs.element.parent().width();this.objs.dims.contentWidth=contentWidth;this.objs.dims.viewableRatio=this.objs.dims.containerWidth/this.objs.dims.contentWidth;this.objs.dims.trackWidth=this.objs.dims.containerWidth;var handleWidth=this.objs.dims.viewableRatio*this.objs.dims.trackWidth;this.objs.handle.css('width',handleWidth);this.objs.dims.maxTrackLeft=this.objs.dims.trackWidth-handleWidth;this.objs.dims.maxLeft=-1*(this.objs.dims.contentWidth-this.objs.dims.containerWidth);if(parseInt(this.objs.handle.css('left'),10)>this.objs.dims.maxTrackLeft){this.objs.handle.css('left',this.objs.dims.maxTrackLeft);this.updatePositionFromTrack(this.objs.dims.maxTrackLeft);}},updatePosition:function(left,animate){left=this.limitSlideX(left);if(this.objs.dims.contentWidth<this.objs.dims.trackWidth){return;}
if(!animate){this.objs.element.css('left',left+'px');}else{this.objs.element.animate({'left':left+'px'},'normal','easeOutExpo');}
var ratio=left/this.objs.dims.contentWidth,trackLeft=-1*this.objs.dims.trackWidth*ratio;this.objs.handle.css('left',trackLeft+'px');},updatePositionFromTrack:function(left){left=this.limitTrackX(left);this.objs.handle.css('left',left+'px');var scrollPercent=this.objs.dims.maxTrackLeft/left,scrollLeft=this.objs.dims.maxLeft/scrollPercent;this.objs.element.css('left',scrollLeft+'px');},updatePositionFromHash:function(){if(virb.site.config.isMobile){return false;}
$item=virb.gallery.getItemByHash();virb.gallery.setItemByHash();var left=-1*$item.position().left;left=this.limitSlideX(left);var ratio=left/this.objs.dims.contentWidth,scrollLeft=-1*this.objs.dims.trackWidth*ratio;if(left>0){left=0;scrollLeft=0;}
if(virb.site.config.isTouch){this.objs.element.css({'left':left+'px'});this.objs.handle.css({'left':scrollLeft+'px'});}else{this.objs.element.stop().animate({'left':left+'px'},500);this.objs.handle.stop().animate({'left':scrollLeft+'px'},500);}},limitSlideX:function(x){if(x<this.objs.dims.maxLeft){x=this.objs.dims.maxLeft;}else if(x>0){x=0;}
return x;},limitTrackX:function(x){if(x<0){x=0;}else if(x>this.objs.dims.maxTrackLeft){x=this.objs.dims.maxTrackLeft;}
return x;},seek:function(e){if(e.target!=this.objs.handle[0]){this.updatePositionFromTrack(e.offsetX);}},dragStart:function(e){$('body').css({cursor:'move'});e.preventDefault();var startX=(Modernizr.touch)?e.originalEvent.touches[0].pageX:e.pageX;this.startX=startX;this.startPosition=this.objs.handle.position().left;this.maxTrackLeft=this.objs.track.width()-this.objs.handle.width();$(document).on('mouseup',$.proxy(this.dragEnd,this));$(document).on('mousemove',$.proxy(this.dragMove,this));$(document).on('touchend',$.proxy(this.dragEnd,this));$(document).on('touchmove',$.proxy(this.dragMove,this));},dragMove:function(e){var x=(Modernizr.touch)?e.originalEvent.touches[0].pageX:e.pageX;this.updatePositionFromTrack(this.startPosition-(this.startX-x));},dragEnd:function(e){$('body').css({cursor:'auto'});$(document).unbind('mouseup',this.dragEnd);$(document).unbind('mousemove',this.dragMove);$(document).unbind('touchend',this.dragEnd);$(document).unbind('touchmove',this.dragMove);},touchScroll:function(e,touch){switch(touch.eventType){case"touchstart":this.startTouchLeft=parseInt(this.objs.element.css('left'),10);break;case"swiperight":case"swipeleft":if(touch.direction!='horizontal'){return false;}
if(touch.isTossed&&false===touch.msTouch){var newX=parseInt(this.objs.element.css('left'),10)+touch.tossOffset.x;this.updatePosition(newX,true);}
break;case"touchmove":if(touch.direction!='horizontal'){return false;}
touch.event.preventDefault();var newX=this.startTouchLeft+touch.offset.x;this.updatePosition(newX);break;}},scroll:function(e,delta){var left=parseInt(this.objs.element.css('left'),10);if($.browser.mozilla){delta=delta*10;}else{delta=e.originalEvent.wheelDeltaX;}
var newX=left+delta;if(Math.abs(delta)>0&&newX<0&&newX>this.objs.dims.maxLeft){e.preventDefault();}
this.updatePosition(newX);}};$.fn.slider=function(){if(false===virb.site.config.isMobile){return this.each(function(){new Slider(this);});}};})();;$(function(){if($.fn.slider!==undefined){$('.horizontal-gallery-container .large-gallery').slider();}
var ie=$('html.ie8, html.ie7');ie.find('#blog ul li:last-child article').addClass('last');ie.find('section.events li:nth-child(2n)').addClass('row-reset');ie.find('.widgets article.widget:nth-child(3n)').addClass('row-reset');ie.find('.listing.grid .listing-list li:nth-child(3n)').addClass('row-reset');ie.find('.listing.grid .listing-list li:nth-child(3n+1)').addClass('clear-reset');ie.find('.grid-gallery .large-gallery li:nth-child(3n)').addClass('row-reset');ie.find('.grid-gallery .large-gallery li:nth-child(3n+1)').addClass('clear-reset');});