(function(){var virb={};virb.site={scriptLoads:[],config:{},objs:{},init:function(args){var self=this;$.each(args,function(key){self.config[key]=args[key];});var $html=$('html');this.config.isTouch=$html.hasClass('touch')||navigator.msMaxTouchPoints?true:false;this.config.msTouch=window.navigator.msPointerEnabled&&navigator.msMaxTouchPoints?true:false,this.config.isIE7=$html.hasClass('ie7')||$html.hasClass('lt-ie8')?true:false;this.config.isIE=$html.hasClass('ie')?true:false;this.config.isRetina=window.devicePixelRatio>1?true:false;if(this.config.isMobile){$html.addClass('is-mobile');}
virb.log(window.devicePixelRatio);this.cart=CartDataManager;this.initObjs();this.attachEvents();},initObjs:function(){this.objs.cartLink=$('.cart-link');this.objs.cartLinkLabel=this.objs.cartLink.find('.label');this.objs.navToggle=$('.toggle a');this.objs.nav=this.objs.navToggle.closest('nav');if(this.cart.getProductCount()>0){this.objs.cartLink.addClass('show-cart');$('.has-store').addClass('show-cart');}
this.objs.cartLinkTotal=$('<span>');this.objs.cartLinkTotalCount=$('<span>',{'class':'total'}).append(this.cart.getProductCount());var paren=$('<span>',{'class':'paren'});this.objs.cartLinkTotal.append(' ').append(paren.clone().append('(')).append(this.objs.cartLinkTotalCount).append(paren.clone().append(')'));this.objs.cartLinkLabel.append(this.objs.cartLinkTotal);},attachEvents:function(){virb.log('site: attach events');var self=this;this.objs.cartLink.bind('update.cart.virb',function(){var count=self.cart.getProductCount();self.objs.cartLinkTotalCount.text(count);});this.objs.navToggle.bind('click',function(e){e.preventDefault();var $this=$(this);var $menu=$('#menu');$menu.css({opacity:0,display:'block',height:'auto'});var listHeight=$menu.outerHeight();if(self.objs.nav.hasClass('open')){$menu.css({opacity:1}).animate({height:0,opacity:0,marginBottom:0},function(){$(this).css({height:0,display:'none'});self.objs.nav.toggleClass('open');});}else{$menu.css({height:0}).animate({opacity:1,height:listHeight},function(){$(this).css({height:'auto'});});self.objs.nav.toggleClass('open');}});$("#menu li.section span").bind('click',function(){var $this=$(this).closest('li');$sectionUl=$this.find('ul:first');$this.toggleClass('open');});},virbUrl:function(path){return'http://'+[this.config.virbDomain,path].join('/');},url:function(path){return'http://'+[this.config.requestDomain,path].join('/');},currentPageUrl:function(){return this.url(this.config.pageUrl);},addScript:function(url){if(!this.scriptLoads[url]){this.scriptLoads[url]=1;}
else
{this.scriptLoads[url]++;}
if(this.scriptLoads[url]<=10){setTimeout(function(){$('script[href^="'+url+'"]').remove();$.getScript(url+'&cacheb='+Math.random());},500);}},trackEvent:function(category,action,label){if(window._gaq){_gaq.push(['_trackEvent',category,action,label]);}}};virb.log=function(){if(virb.site.config.debug){try{var args=Array.prototype.slice.call(arguments),log=Function.prototype.bind.call(console.log,console);log.apply(this,args);}catch(e){}}};virb.cookie=function(key,value,options){if(arguments.length>1&&(!/Object/.test(Object.prototype.toString.call(value))||value===null||value===undefined)){options=$.extend({},options);if(value===null||value===undefined){options.expires=-1;}
if(typeof options.expires==='number'){var days=options.expires,t=options.expires=new Date();t.setDate(t.getDate()+days);}
value=String(value);return(document.cookie=[encodeURIComponent(key),'=',options.raw?value:encodeURIComponent(value),options.expires?'; expires='+options.expires.toUTCString():'',options.path?'; path='+options.path:'',options.domain?'; domain='+options.domain:'',options.secure?'; secure':''].join(''));}
options=value||{};var decode=options.raw?function(s){return s;}:decodeURIComponent;var pairs=document.cookie.split('; ');for(var i=0,pair;pair=pairs[i]&&pairs[i].split('=');i++){if(decode(pair[0])===key){return decode(pair[1]||'');}}
return null;};var CartDataManager={add:function(product){var products=this.getProducts();if(!products[virb.store.getType()]){products[virb.store.getType()]=[];}
products[virb.store.getType()].push(product);this.saveState(JSON.stringify(products));$.event.trigger('update.cart.virb');},remove:function(type,uid){var products=this.getProducts();for(var i=0;i<products[type].length;i++){if(products[type][i].u===uid){products[type].splice(i,1);}}
this.saveState(JSON.stringify(products));$.event.trigger('update.cart.virb');$.event.trigger('itemRemoved.cart.virb',[uid]);},empty:function(type){var products=this.getProducts();delete products[type];this.saveState(JSON.stringify(products));$.event.trigger('update.cart.virb');},saveState:function(data){virb.log(data);virb.cookie('products',data,{expires:7,path:'/'});},getProducts:function(){var products=virb.cookie('products');if(products){products=$.parseJSON(products);if(products.etsy||products.bigcartel){return products;}}
return{};},getProductCount:function(){var products=this.getProducts(),total=0;$.each(products,function(key,value){total+=value.length;});return total;},getTotal:function(type){var products=this.getProducts(),total=0;if(products[type]){for(var i=0;i<products[type].length;i++){total+=products[type][i].p*1;}}
return total.toFixed(2);}};iconMap={'ie7':{"⏩":"›","⏪":"‹","ⅱ":"ll","▶":">","×":"x"},'winPhone7':{"⏩":"›","⏪":"‹","ⅱ":"ll"}}
$.fn.fixIcons=function(){return this.each(function(){var $this=$(this);if(false!==virb.site.config.isIE7){swapIcons($this,'ie7');$this.addClass('data-icon').prepend('<span>'+$this.data('icon')+'</span>');}else if(false!==virb.site.config.isWindowsPhone7){swapIcons($this,'winPhone7');}});};var swapIcons=function($element,mapKey){$.each(iconMap[mapKey],function(index,value){if(escape(index)==escape($element.data('icon'))){$element.attr({'data-icon':value});$element.data({'icon':value});}else if(escape(index)==escape($element.data('icon-pause'))){$element.attr({'data-icon-pause':value});$element.data({'icon-pause':value});}});};$.fn.disableSelection=function(){return this.attr('unselectable','on').css('user-select','none').on('selectstart',false);};String.prototype.truncate=function(length){var str=''+this;if(str.length>length){return str.substring(0,length)+'&hellip;';}
return str;};getFlashMovie=function(movieName){var isIE=navigator.appName.indexOf("Microsoft")!=-1;flashMovie=(isIE)?window[movieName]:document[movieName];return flashMovie;}
aspectRatio=function(originalWidth,originalHeight,args){if(0==originalHeight||0==originalWidth){virb.log('Aspect ratio, Width: '+originalWidth+' Height: '+originalHeight);return{'width':originalWidth,'height':originalHeight};}
var height=originalHeight;var width=originalWidth;if(args.targetHeight){ratio=args.targetHeight/originalHeight;}else{ratio=args.targetWidth/originalWidth;}
if(args.targetHeight){height=args.targetHeight;width=Math.floor(originalWidth*ratio);}else{width=args.targetWidth;height=Math.floor(originalHeight*ratio);}
return{'width':width,'height':height};}
$(".share-label").click(function(){$(this).parent().parent().toggleClass("open");});window.virb=virb;$(function(){var getShareCount=function($share){var fullUrl;var shareUrl=$share.closest('.share-buttons').data('share-url');var type=$share.attr('class');switch(type){case'facebook':fullUrl='http://graph.facebook.com/?id='+shareUrl+'&callback=';break;case'twitter':fullUrl='http://cdn.api.twitter.com/1/urls/count.json?url='+shareUrl+'&jsonp=';break;case'linkedin':fullUrl='http://www.linkedin.com/countserv/count/share?format=jsonp&url='+shareUrl+'&jsonp=';break;case'pinterest':fullUrl='http://widgets.pinterest.com/v1/urls/count.json?url='+shareUrl+'&jsonp=';break;default:return;break;}
$.ajax({url:fullUrl,type:'GET',dataType:"jsonP",success:function(result){handleShareCount($share,result);}});};var handleShareCount=function($share,result){var count=0;var type=$share.attr('class');var $count=$share.find('.count');switch(type){case'facebook':if(result.shares){count=result.shares;}
break;case'twitter':case'linkedin':case'pinterest':if(result.count){count=result.count;}
break;default:return;break;}
$count.html(count);if(count>0){$count.show();}};$('.share-buttons').each(function(){$this=$(this);var shareUrl=$this.data('share-url');$this.find('li').each(function(){getShareCount($(this));});});virb.site.init(siteSettings);if(parent!==window){try{parent.virb.$.customize.pageReady(virb.site.config.pageUrlId);}catch(e){}}
$('[data-icon]').fixIcons();});})();;(function(){var useFlash=(false===(Modernizr.audio&&Modernizr.audio.mp3!==''));var Player=function(element){this.objs={};var self=this;if(useFlash){if($('#virbMedia').length===0){this.addFlashPlayer(function(){self.objs.flashMovie=$('#virbAudioPlayer')[0];});}else{self.objs.flashMovie=$('#virbAudioPlayer')[0];}}
this.objs.element=$(element);this.objs.tracks=[];this.objs.element.data('audio-player',this);this.objs.element.data('singular',(this.objs.element.attr('data-behavior')==='singular-control'));this.objs.element.find('ol li').each(function(i){self.objs.tracks.push(new Track(self,this));});};Player.prototype={singularControl:false,constructor:Player,addFlashPlayer:function(callback)
{$('body').prepend('<div class="media virbMedia" style="position:absolute;"><span id="replace_mediaAudioPlayer"></span></div>');var flashvars={virb_domain_secure:'http://'+virb.site.config.virbDomain};var params={name:'virbAudioPlayer',allowScriptAccess:'always',wmode:'transparent'};var attributes={wmode:'transparent',bgcolor:'',name:'virbAudioPlayer',id:'virbAudioPlayer'};swfobject.embedSWF('http://'+virb.site.config.virbCDNDomain+'/_assets/_swf/virb_audio_js.swf','replace_mediaAudioPlayer',"1","1","9.0.0",false,flashvars,params,attributes,callback);}};var Track=function(player,track){this.objs={};this.objs.player=player;this.objs.element=$(track);this.objs.audio=this.objs.element.find('audio');this.objs.time=this.objs.element.find('.time');this.objs.barContainer=this.objs.element.find('.length');this.objs.amountPlayed=this.objs.element.find('.length .progress');this.objs.amountLoaded=this.objs.element.find('.length .load');this.objs.playButton=this.objs.element.find('.controls .play-pause');this.objs.nextButton=this.objs.element.find('.controls .next');this.objs.prevButton=this.objs.element.find('.controls .previous');this.objs.element.data('audio-player-track',this);this.objs.playButton.bind('click',$.proxy(this.select,this));this.objs.element.bind('play.audio.virb',$.proxy(this.pauseSelf,this));if(this.objs.player.objs.element.data('singular')){this.objs.nextButton.bind('click',$.proxy(this.next,this));this.objs.prevButton.bind('click',$.proxy(this.previous,this));}
this.objs.audio.bind('timeupdate',$.proxy(this.updatePlayhead,this));this.objs.audio.bind('progress',$.proxy(this.updateBufferProgress,this));this.objs.audio.bind('ended',$.proxy(this.ended,this));};Track.prototype={constructor:Track,updatePlayhead:function(){var audio=this.objs.audio.get(0),duration=audio.duration,current=audio.currentTime,progress=(current/duration)*100,mins=parseInt(current/60,10),secs=parseInt(current-(mins*60),10);if(secs<10){secs='0'+secs;}
if(progress>=0){this.objs.amountPlayed.css({width:progress+'%'});}
this.objs.time.html(mins+':'+secs);},updateBufferProgress:function(){try{var audio=this.objs.audio.get(0),loaded=parseInt(((audio.buffered.end(0)/audio.duration)*100),10);if(loaded>=0){this.objs.amountLoaded.css({width:loaded+'%'});}}catch(e){}},seek:function(e){var ratio=(e.pageX-this.objs.barContainer.offset().left)/this.objs.barContainer.width(),track=this.objs.element;if(useFlash){this.objs.player.objs.flashMovie.seekTo(track.attr('data-uid'),ratio*100);return;}
var audio=this.objs.audio.get(0),duration=audio.duration;audio.currentTime=duration*ratio;},ended:function(e){virb.log('track ended');this.objs.amountPlayed.css({width:'0%'});this.objs.time.html('0:00');this.objs.audio.get(0).pause();this.objs.playButton.removeClass('pause');this.objs.audio.get(0).currentTime=0;var next=this.objs.element.next();if(next.length>0){this.next(e);}
return;},select:function(e){virb.log('select track');if(e!==undefined){e.preventDefault();}
var track=this.objs.element,id=track.attr('data-id'),uid=track.attr('data-uid'),playButton=this.objs.playButton,audio=this.objs.audio.get(0);track.show();this.objs.barContainer.bind('click',$.proxy(this.seek,this));if(useFlash){var movie=this.objs.player.objs.flashMovie,service='song';if(track.attr('data-source')!==undefined&&track.attr('data-source')!='virb'){service=track.attr('data-source');}
movie.retrieveSong(track.attr('data-uid'),track.attr('data-id'),service);virb.$.audio.updateLoader=function(uid,loaded){track.find('.length .load').css({width:loaded+'%'});};virb.$.audio.updateTime=function(time,uid){track.find('.time').html(time);};virb.$.audio.updateProgress=function(progress,uid){track.find('.length .progress').css({width:progress+'%'});};}else{if(audio.paused){audio.play();$.event.trigger('play.audio.virb',[track]);playButton.addClass('pause');track.addClass('playing');track.removeClass('paused');if(track.attr('data-title')){virb.site.trackEvent('Audio','Play',track.attr('data-title'));}}else{audio.pause();$.event.trigger('pause.audio.virb',[track]);playButton.removeClass('pause');track.addClass('paused');track.removeClass('playing');}}
var self=this,playerElement=this.objs.player.objs.element;if(playerElement.data('singular')){var tracks=playerElement.data('audio-player').objs.tracks;$.each(tracks,function(i,value){if(value!==self){value.objs.element.hide();}});}},next:function(e){virb.log('next track');e.preventDefault();var next=this.objs.element.next();if(next.length===0){this.objs.nextButton.css('opacity',0.5);return;}
next.data('audio-player-track').select();},previous:function(e){e.preventDefault();var prev=this.objs.element.prev();if(prev.length===0){this.objs.prevButton.css('opacity',0.5);return;}
prev.data('audio-player-track').select();},pauseSelf:function(e,$track){if($track!==this.objs.element){this.objs.audio.get(0).pause();this.objs.playButton.removeClass('pause');}}};virb.$={audio:{}};$(function(){$('.audio-player').each(function(){new Player(this);});if(useFlash){$(document).bind('playing.track.event.audio.virb',function(e,uid){var element=$(this).find('.audio-player ol li[data-uid="'+uid+'"]');element.data('audio-player-track').objs.playButton.addClass('pause');});$(document).bind('pause.track.event.audio.virb',function(e,uid){var element=$(this).find('.audio-player ol li[data-uid="'+uid+'"]');element.data('audio-player-track').objs.playButton.removeClass('pause');});}});})();;$(function(){if($.fn.slider!==undefined){$('.horizontal-gallery-container .large-gallery').slider();}
var ie=$('html.ie8, html.ie7');ie.find('#blog ul li:last-child article').addClass('last');ie.find('section.events li:nth-child(2n)').addClass('row-reset');ie.find('.widgets article.widget:nth-child(3n)').addClass('row-reset');ie.find('.listing.grid .listing-list li:nth-child(3n)').addClass('row-reset');ie.find('.listing.grid .listing-list li:nth-child(3n+1)').addClass('clear-reset');ie.find('.grid-gallery .large-gallery li:nth-child(3n)').addClass('row-reset');ie.find('.grid-gallery .large-gallery li:nth-child(3n+1)').addClass('clear-reset');});